# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from fusion_identity.grpc import identity_pb2 as identity__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in identity_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IdentityServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AuthorizeAndAcquire = channel.unary_unary(
                '/fusion.identity.v1.IdentityService/AuthorizeAndAcquire',
                request_serializer=identity__pb2.AuthorizeAndAcquireRequest.SerializeToString,
                response_deserializer=identity__pb2.AuthorizeAndAcquireResponse.FromString,
                _registered_method=True)
        self.ReleaseLease = channel.unary_unary(
                '/fusion.identity.v1.IdentityService/ReleaseLease',
                request_serializer=identity__pb2.ReleaseLeaseRequest.SerializeToString,
                response_deserializer=identity__pb2.ReleaseLeaseResponse.FromString,
                _registered_method=True)
        self.ReportUsage = channel.unary_unary(
                '/fusion.identity.v1.IdentityService/ReportUsage',
                request_serializer=identity__pb2.ReportUsageRequest.SerializeToString,
                response_deserializer=identity__pb2.ReportUsageResponse.FromString,
                _registered_method=True)


class IdentityServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def AuthorizeAndAcquire(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseLease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IdentityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AuthorizeAndAcquire': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthorizeAndAcquire,
                    request_deserializer=identity__pb2.AuthorizeAndAcquireRequest.FromString,
                    response_serializer=identity__pb2.AuthorizeAndAcquireResponse.SerializeToString,
            ),
            'ReleaseLease': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseLease,
                    request_deserializer=identity__pb2.ReleaseLeaseRequest.FromString,
                    response_serializer=identity__pb2.ReleaseLeaseResponse.SerializeToString,
            ),
            'ReportUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportUsage,
                    request_deserializer=identity__pb2.ReportUsageRequest.FromString,
                    response_serializer=identity__pb2.ReportUsageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fusion.identity.v1.IdentityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fusion.identity.v1.IdentityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IdentityService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AuthorizeAndAcquire(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fusion.identity.v1.IdentityService/AuthorizeAndAcquire',
            identity__pb2.AuthorizeAndAcquireRequest.SerializeToString,
            identity__pb2.AuthorizeAndAcquireResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fusion.identity.v1.IdentityService/ReleaseLease',
            identity__pb2.ReleaseLeaseRequest.SerializeToString,
            identity__pb2.ReleaseLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fusion.identity.v1.IdentityService/ReportUsage',
            identity__pb2.ReportUsageRequest.SerializeToString,
            identity__pb2.ReportUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
